[tool.ruff]
line-length = 88
target-version = "py312"
extend-select = ["E","F","I","UP","B","SIM","PL"]
ignore = []
fix = true
unsafe-fixes = true

[tool.ruff.lint.isort]
known-first-party = ["recommender","storage","app"]

[tool.black]
line-length = 88
target-version = ["py312"]
